@echo off
echo Starting backend services...

echo Starting auth-service...
start "Auth Service" cmd /k "cd /d G:\听说\packages\auth-service && npx ts-node -r dotenv/config src/index.ts dotenv_config_path=.env"

echo Starting user-service...
start "User Service" cmd /k "cd /d G:\听说\packages\user-service && npx ts-node -r dotenv/config src/index.ts dotenv_config_path=.env"

echo Starting practice-service...
start "Practice Service" cmd /k "cd /d G:\听说\packages\practice-service && npx ts-node -r dotenv/config src/index.ts dotenv_config_path=.env"

echo Starting evaluation-service...
start "Evaluation Service" cmd /k "cd /d G:\听说\packages\evaluation-service && npx ts-node -r dotenv/config src/index.ts dotenv_config_path=.env"

echo Starting scheduling-service...
start "Scheduling Service" cmd /k "cd /d G:\听说\packages\scheduling-service && npx ts-node -r dotenv/config src/index.ts dotenv_config_path=.env"

echo Starting analytics-service...
start "Analytics Service" cmd /k "cd /d G:\听说\packages\analytics-service && npx ts-node -r dotenv/config src/index.ts dotenv_config_path=.env"

echo All services starting...
